### ISSUE TITLE
Error processing platform mediabrowser.media_source

### ISSUE THREAD

**Issue by holdestmade** [rumbu13/ha-mediabrowser#5]
### System Health details

Home Assistant 2023.5.4
Supervisor 2023.05.0
Operating System 10.1
Frontend 20230503.3 - latest

### Checklist

- [ ] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Getting this on startup

### Reproduction steps

1. NA
2.
3.
...

### Debug logs

```text
Logger: homeassistant.helpers.integration_platform
Source: custom_components/mediabrowser/media_source.py:44
Integration: MediaBrowser (Emby/Jellyfin) integration (documentation, issues)
First occurred: 08:52:10 (1 occurrences)
Last logged: 08:52:10

Error processing platform mediabrowser.media_source
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 61, in _async_process_single_integration_platform_component
    await integration_platform.process_platform(hass, component_name, platform)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 88, in _process_media_source_platform
    hass.data[DOMAIN][domain] = await platform.async_get_media_source(hass)
  File "/config/custom_components/mediabrowser/media_source.py", line 44, in async_get_media_source
    hubs = [hass.data[DOMAIN][entry.entry_id][DATA_HUB] for entry in entries]
  File "/config/custom_components/mediabrowser/media_source.py", line 44, in <listcomp>
    hubs = [hass.data[DOMAIN][entry.entry_id][DATA_HUB] for entry in entries]
KeyError: 'mediabrowser'
```

**Comment by rumbu13** [comment]
I think this is the fault of Home Assistant, it is trying to load the media source component before loading the config entries. Sincerely I have no idea how to solve this, theoretically this should not happen.

**Comment by holdestmade** [comment]
Ok no worries I'll put an ignore in my logger
